language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
#install: "pip install -r requirements.txt"
install: pip install pycparser
# command to run tests
script: ./test_mockify.py
